apiVersion: v1
kind: Service
metadata:
  name: java-app-svc
    labels:
      app: java-app
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: java-app    
---
apiVersion: v1
kind: Deployment
metadata:
  name: java-app-deployment
  labels:
    app: java-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
  spec:
    containers:
      - name: java-app-container
        image: avesahmed/new-java-app      
        env:
          - name: DB_URL
            value: "jdbc:mysql://mysql:3306/mydatabase?useSSL=false&allowPublicKeyRetrieval=true"
          - name: DB_USERNAME
            value: "myuser"
          - name: DB_PASSWORD
            value: "your-secure-password"
        ports:
          - containerPort: 8080