apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: mysql
spec:
  ports:
    - 3306
  selector:
    app: mysql
  cluserIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec: 
    containers:
      - name: mysql
        image: mysql:8.0
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "your-secure-password"
          - name: MYSQL_DATABASE
            value: "mydatabase"
          - name: MYSQL_USER
            value: "myuser"
          - name: MYSQL_PASSWORD
            value: "your-secure-password"
        ports:
          - containerPort: 3306    

